// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://oqyphsalgmgtnipxtbyr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9xeXBoc2FsZ21ndG5pcHh0YnlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzOTI5MTAsImV4cCI6MjA3Mzk2ODkxMH0._nLAJNiDRDYVm-7np8K0gW0EeEhCXue7y_Hgcj8pEFI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);